Lambda-School-Labs/CS10-job-board

README.md
We added a README.md file to initialize the project.
=> added README.md to initialize project

frontend/job-board/package.json, frontend/job-board/yarn.lock
Added axios and react-router-dom dev dependencies. 
Package.json:
=> Add axios & react-router-dom dependencies

backend/jobs/api.py, backend/jobs/models.py, backend/jobsboard/settings.py
- Fix inability to create superuser
- Can now login to Django Admin
=> Modify user model to allow creation of superuser

jobs/MODELS.md, jobs/admin.py, jobs/models.py
Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Got run server and create superuser working on this build. You just have to run ./manage.py [command] from root folder.
=> Sagar Desai

jobsboard/settings.py
Add whitenoise to server for proper deploy.
- Compared settings.py to [deploy repo ](https://github.com/cs10jobboard/cs10-job-board-deployment/blob/master/jobsboard/settings.py) to make sure it was proper
=> Add whitenoise

frontend/src/components/auth/Login.js, frontend/src/components/auth/Register.js, frontend/src/css/Landing.css
Added Ant-Design Forms with Icons for Email/Password/Name. Replaced custom tooltips with Ant-Design tooltips.
=> Ant design additions

README.md, frontend/src/App.js, frontend/src/components/auth/Login.js, frontend/src/components/auth/Register.js, frontend/src/css/AntDesignOverride.css, frontend/src/css/App.css, frontend/src/css/Landing.css
- Added a css file to override antd classes as needed, and reworked css imports to ensure correct override specificity. 
1. Cleaned up landing page form styling & icons.
2. Fixed login or register message if navigating to a route without being authenticated to not show when loading the landing page.
Updated forms:
Fixed error message to only show when being redirected:
=> Add antd css override file & bug / styling fixes

jobs/urls.py, jobs/views.py, jobsboard/urls.py
Setting up membership select view.
Was able to run server, non breaking update.
=> getting the membership types view set up

frontend/src/App.js, frontend/src/components/Avatar.js, frontend/src/components/EmployerProfile.js, frontend/src/components/index.js, frontend/src/css/EmployerProfile.css
- Added basic profile page for employer
- Styling needs some work
=>  Create Profile Page (Employer)

jobs/api.py, jobs/models.py, jobs/views.py
Reverts Lambda-School-Labs/CS10-job-board#39
=> Revert "worked on account view and added plan_description to Membership class"

frontend/src/App.js, jobs/models.py, jobs/urls.py, jobs/views.py, jobsboard/settings.py
Change JWT verify to refresh api in App.js, to refresh tokens if they are valid. If token is not valid, logs out. 
Move the JWT handler functions to views.py
Login still functions after app restart.
=> JWT Refresh

jobs/api.py, jobs/urls.py, jobs/views.py, jobsboard/settings.py
- Sets custom auth based on classes of Views. Job list and individual job views no longer require auth to access the backend API. (Frontend work still needed)
- Cleans up imports across several files
Jobs List View in Incognito(non-auth) mode:
Individual Job View:
=> Custom auth routes

frontend/src/App.js, frontend/src/components/CompanyLanding.js, frontend/src/components/Job.js, frontend/src/components/JobList.js, frontend/src/components/Landing.js, frontend/src/components/auth/Login.js, frontend/src/components/utility/Navigation.js, frontend/src/css/AntDesignOverride.css, frontend/src/css/App.css, frontend/src/css/CompanyLanding.css, frontend/src/css/JobList.css, frontend/src/css/Landing.css, frontend/src/css/Login.css
Styling added to nearly all currently functional front-end components.
Bug in 'GET' Request for jobs by id unresolved
=> Styling and Functionality added

README.md, frontend/src/App.js, frontend/src/components/JobPost.js, frontend/src/components/TagCreate.js, frontend/src/components/utility/Navigation.js, jobs/api.py, jobs/views.py, jobsboard/urls.py
- Posting a job API now fulfills MVP requirements. 🥇 
- Publishes on demand, when modal is closed, form is reset (this was so difficult working with ant-d).
- Add Auth API documentation
- Add Network error handling on App reload: does not remove JWT if Internet disappears or server is down
- JWT payload carries the id of the user, which fixed the ForeignKey problem when posting.
Multiple Job Posting without app reload:
Network error message:
=> Fix Job POST API: fulfills MVP req's

README.md, frontend/src/components/auth/Login.js, frontend/src/components/auth/Register.js, frontend/src/components/job/JobPost.js, jobs/api.py, jobs/models.py, jobs/permissions.py, jobs/urls.py, jobs/views.py, jobsboard/urls.py
1. api/job/id is now restricted to only a GET request
2. api/company/jobs/ now accepts a POST request (replaces /api/addjob/)
3. api/company/jobs/ requires authentication, and checks request field 'company' to ensure id matches the id of the authenticated user. Otherwise it returns a 403 Forbidden.
Fixes # (#94 )
Adds reset messages / errors on Login.js and Register.js
Adds null=True to company_logo in models.py
Postman tests of new api functionality:
**POST to api/job/:id**
---
**GET to api/company/jobs/ without authentication:**
---
**GET to api/company/jobs/ with …
=> Restrict JobAPI & Modify jobs API

README.md, frontend/src/components/auth/Login.js, frontend/src/components/auth/Register.js, frontend/src/components/job/JobPost.js, jobs/api.py, jobs/models.py, jobs/permissions.py, jobs/urls.py, jobs/views.py, jobsboard/urls.py
1. Adds Jobs API `api/company/jobs/:id/`
2. Protected API route, requires authentication.
3. Any auth user can access GET
4. Only user whose id matches the returned job's company id field can make PUT, PATCH, DELETE requests
5. Handling is done with ModifyJobPost in views.py, and path('company/jobs/<int:pk>/') in urls.py
Fixes # (#83 )
Postman:
---
GET w/o AUTH:
---
GET w/ AUTH:
---
PUT w/o AUTH:
---
PUT w/ AUTH:
---
PATCH w/ AUTH:
---
PATCH w/o AUTH:
---
DELETE w/ AUTH:
---
DELETE w/o AUTH:
---
FORBIDDEN (checking ids and job company field id):
=> Add Company Modify JobPost API: `/api/company/jobs/:id/`

frontend/src/components/job/JobList.js, jobs/api.py, jobs/permissions.py, jobs/utils.py, jobs/views.py
- Added pagination and permissions in Django
- Setup unique slug generator (for later implementation)
Fixes #74
=> Add Pagination to Django

README.md, frontend/src/components/company/CompanyDashboard.js, frontend/src/components/company/CompanyJobCounter.js, frontend/src/components/company/CompanyJobList.js, frontend/src/components/job/JobList.js, jobs/api.py, jobs/jwt_config.py, jobs/models.py, jobs/urls.py, jobs/views.py
1. Adds `api/account/:id`. Accepts GET, PUT, PATCH, DELETE requests from only the user themselves.
2. Adds jwt_config.py for later cutomization of encoded payload data on the JWT.
3. Adds comments throughout database files for clarity
4. Cleans up old code no longer in use.
5. Adds pagination to CompanyJobList.js component
6. Reworks CompanyDashboard/CompanyJobList/CompanyJobCount component structure.
7. Updates Readme
Fixes # (#102 )
- Removes unnecessary jobs state in JobList.js
- Uses the `__all__` option in UserViewSerializer & JobPostSerializer
- Adds null=True to company_logo & profile_photo
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for …
=> Update User API: Adds `/api/account/:id`

frontend/.babelrc, frontend/src/components/utility/Avatar.js, frontend/src/tests/Account.test.js, frontend/src/tests/App.test.js, frontend/src/tests/Billing.test.js, frontend/src/tests/CompanyLanding.test.js, frontend/src/tests/CompanyRegister.test.js, frontend/src/tests/Dashboard.test.js, frontend/src/tests/Job.test.js, frontend/src/tests/Landing.test.js, frontend/src/tests/Login.test.js, frontend/src/tests/Register.test.js
Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> Enzyme registerlanding - added tests for component presence

frontend/.babelrc, frontend/src/components/index.js, frontend/src/components/utility/Avatar.js, frontend/src/tests/Account.test.js, frontend/src/tests/App.test.js, frontend/src/tests/Billing.test.js, frontend/src/tests/CompanyDashboard.test.js, frontend/src/tests/CompanyJobList.test.js, frontend/src/tests/CompanyLanding.test.js, frontend/src/tests/CompanyProfile.test.js, frontend/src/tests/CompanyRegister.test.js, frontend/src/tests/Dashboard.test.js, frontend/src/tests/Job.test.js, frontend/src/tests/Landing.test.js, frontend/src/tests/Login.test.js, frontend/src/tests/Register.test.js
add tests for company components, need to test for functional components
=> Enzyme companytests - add company tests

frontend/src/tests/app_test/App.test.js, frontend/src/tests/auth_test/CompanyLanding.test.js, frontend/src/tests/auth_test/CompanyRegister.test.js, frontend/src/tests/auth_test/Landing.test.js, frontend/src/tests/auth_test/Login.test.js, frontend/src/tests/auth_test/Register.test.js, frontend/src/tests/billing_test/Billing.test.js, frontend/src/tests/billing_test/CheckoutForm.test.js, frontend/src/tests/company_test/CompanyDashboard.test.js, frontend/src/tests/company_test/CompanyJobCounter.test.js, frontend/src/tests/company_test/CompanyJobList.test.js, frontend/src/tests/company_test/CompanyProfile.test.js, frontend/src/tests/job_test/Job.test.js, frontend/src/tests/job_test/JobList.test.js, frontend/src/tests/job_test/JobPost.test.js, frontend/src/tests/job_test/JobPreview.test.js, frontend/src/tests/job_test/TagCreate.test.js, frontend/src/tests/job_test/TagView.test.js, frontend/src/tests/seeker_test/Account.test.js, frontend/src/tests/seeker_test/Dashboard.test.js, frontend/src/tests/utility_test/Avatar.test.js, frontend/src/tests/utility_test/Navigation.test.js, frontend/src/tests/utility_test/NoMatch.test.js, frontend/src/tests/utility_test/Search.test.js
testing remaining functional components and stripe component, organized tests
=> Enzyme stateless - stripe component tested 

README.md, frontend/package.json, frontend/src/App.js, frontend/src/components/company/CompanyAccount.js, frontend/src/components/index.js, frontend/src/components/seeker/Account.js, frontend/src/components/utility/LogoutAll.js, frontend/src/css/AntDesignOverride.css, frontend/src/css/CompanyAccount.css, frontend/src/css/LogoutAll.css, frontend/src/css/index.css, frontend/yarn.lock
Button that resets JWT secret signature on user model if pressed. 
Logs out user to sign in page. 
Fixes # (#86 )
=> Add LogoutAll.js : resets JWT secret on user model

README.md
The website that is linked on the readme was spelled wrong. I decided to fix the link to the website.
=> Fixes the link to the website.

README.md, frontend/src/components/company/CompanyDashboard.js, frontend/src/components/company/CompanyJobBalance.js, frontend/src/components/company/CompanyJobCounter.js, frontend/src/components/company/CompanyJobList.js, frontend/src/components/index.js, frontend/src/components/job/JobList.js, frontend/src/components/job/JobPreview.js, frontend/src/css/AntDesignOverride.css, frontend/src/css/App.css, frontend/src/css/CompanyJobBalance.css, frontend/src/css/CompanyJobList.css, frontend/src/css/Dashboard.css, frontend/src/css/JobList.css, frontend/src/css/index.css, jobs/views.py, jobsboard/settings.py, requirements.txt, seeder.py
- Adds api request query param handling for CompanyJobList
- Adds ability to delete a job post & batch delete
- Adds UI display density dropdown menu
- Reworks search UI
- Fixes CSS
- Adds a Stripe skeleton component
- Adds updated Heroku deployement docs
- Adds CompanyJobBalance & css file for Stripe API calls
- Removes some plural css classes 👎 
- Adds CompanyPostPageNumberPagination class to views.py for pagination settings for company user
- Adds factory-boy to requirements.txt
- Adds a default pagination class to settings.py
- Sets the default password for fake user accounts to TESTACCOUNT for ease of access
Fixes # (#75 )
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also …
=> Update CompanyJobList.js functionality & other misc. tasks

frontend/public/index.html, frontend/src/App.js, frontend/src/components/auth/CompanyLanding.js, frontend/src/components/auth/CompanyRegister.js, frontend/src/components/auth/Landing.js, frontend/src/components/billing/Billing.js, frontend/src/components/billing/CheckoutForm.js, frontend/src/components/company/CompanyAccount.js, frontend/src/components/company/CompanyDashboard.js, frontend/src/components/company/CompanyJobList.js, frontend/src/components/job/JobPost.js, frontend/src/components/seeker/Account.js, frontend/src/components/utility/AccountUpdate.js, frontend/src/components/utility/LogoutAll.js, frontend/src/components/utility/Navigation.js, frontend/src/css/AntDesignOverride.css, frontend/src/css/App.css, frontend/src/css/CompanyJobList.css, frontend/src/css/Landing.css, jobs/admin.py, jobs/api.py, jobs/models.py, jobs/notes/MODELS.md, jobs/tests/test_models.py, jobs/tests/test_views.py, jobs/urls.py, jobs/views.py
- Implements basic charge handling for Job Posts & Unlimited Subscription.
- Does not implement data retrieval / display from Stripe in FE app.
- Checkout with 4242 4242 4242 4242 and any nums other fields to test. 
- All keys for Stripe should be the test keys. 
- Other CRUD operations for Stripe are not handled yet. 
- Form needs styling.
- Changes App background color
- Fixes a lot of React warnings
- Simplifies Billing / CheckoutForm architecture 
- Comments out Subscription model & associated code / deletes Imports
- Reworks models: Payment -> UserPayment
- Commented throughout code for explanation
- Removes checkToken from FE (unnecessary)
Fixes # (#76 )
Please describe the tests that you ran to verify your changes. Provide instructions …
=> Stripe MVP

fakerdata.py, jobs/models.py, jobs/views.py, jobsboard/settings.py, seeder.py
Updates faker data to create UserMembership objects for fake employer accounts.
Memberships created after:
Job List:
=> Update faker data

frontend/src/components/company/CompanyJobBalance.js, frontend/src/components/company/CompanyJobEdit.js, frontend/src/components/company/CompanyJobList.js, frontend/src/components/job/TagCreate.js, seeder.py
Updates list management by removing DOM queries and implementing new data structures to handle complexity.
Updates state property names for clarity and refactors handler functions into HOF.
- Bug fixed when removing a tag in an existing job. 
- Bug fixed displaying job credit. 
Made sure all existing functionality was not compromised:
- Check all
- Delete job(s)
- Edit jobs
=> Refactor CompanyJobList.js
